auto-labels:
  docs:
    - docs/en/docs/**
    - docs_src/**
  lang-all:
    - docs/*/docs/**
  infra:
    - .github/workflows/**
  internal:
    - exclude: .github/ignored/**
    - .github/**
    - scripts/**
    - uv.lock
