name: Notify Translations

on:
  pull_request_target:
    types:
      - labeled

jobs:
  notify-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          persist-credentials: false
      # Allow debugging with tmate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - uses: ./.github/actions/notify-translations
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
